import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {

  constructor() { }


  private mockData = [
    {
      id: 1,
      account: "0000001",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 1,
      account: "0000002",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 3,
      account: "0000003",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 4,
      account: "0000004",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 5,
      account: "0000005",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 6,
      account: "0000006",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 7,
      account: "0000007",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 8,
      account: "0000008",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 9,
      account: "0000009",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 10,
      account: "0000010",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 11,
      account: "0000011",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 12,
      account: "0000012",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 13,
      account: "0000013",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 14,
      account: "0000014",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    },
    {
      id: 15,
      account: "0000015",
      operation: "Buy",
      symbol: "NA",
      description: "NATIONAL BANK OF CDA",
      qty: 11,
      filledQty: 1,
      price: 135.00,
      status: "Waiting",
      date: "2022/12/22 03:02:14",
      expiration: "2022/12/22 03:02:14",
      no_ref: "965827123",
      ext_ref: "2-XXXXXX1-0",
      firstName: "John",
      lastName: "Doe",
      netAmount: 1000,
      exchangeRate: 10.281,
      osLimit: 140.0,
      telephone: "000-000-000",
      userId: "123",
      warnings: [
        "To trade this security in this account, a currency conversion will be made at the current rate.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus ",
        "Reiciendis. Explicabo quis iure odio officia sapiente, ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum.",
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias libero ea quo doloribus reiciendis. ",
        "Dolor impedit soluta ex dolores necessitatibus fugiat quaerat tempore earum."
      ],
      isOpen: false
    }
  ];

  getMockData(): Observable<any[]> {
    return of(this.mockData);
  }
}
